local Plug = vim.fn['plug#']
Plug('bluz71/vim-moonfly-colors', { ['as'] = 'moonfly' })
Plug('nvim-treesitter/nvim-treesitter')
Plug("nvim-treesitter/nvim-treesitter-context")
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug("mason-org/mason.nvim")
Plug("nvim-lua/plenary.nvim")
Plug("MunifTanjim/nui.nvim")
Plug("nvim-neo-tree/neo-tree.nvim", { ['branch'] = "v3.x" })
Plug("nvim-telescope/telescope-fzf-native.nvim", { ['do'] = 'make' })
Plug('nvim-telescope/telescope.nvim')
Plug('windwp/nvim-autopairs')
Plug('https://github.com/nvimdev/indentmini.nvim')
Plug('nvim-mini/mini.nvim')
Plug("rafamadriz/friendly-snippets")
Plug("saghen/blink.lib")
Plug("saghen/blink.cmp")
Plug("hiphish/rainbow-delimiters.nvim")
Plug("folke/which-key.nvim")
Plug("neovim/nvim-lspconfig")
Plug("WieeRd/auto-lsp.nvim")
Plug("lewis6991/gitsigns.nvim")
Plug("folke/edgy.nvim")
Plug("barrettruth/live-server.nvim")
Plug("windwp/nvim-ts-autotag")
Plug("vyfor/cord.nvim")
Plug("ray-x/lsp_signature.nvim")
Plug("folke/noice.nvim")
Plug("akinsho/toggleterm.nvim")
