splash = false
wallpaper {
    monitor = DP-1
    path = /home/rey/Pictures/1669954221209850.png
    fit_mode = fill
}
wallpaper {
    monitor = DP-2
    path = /home/rey/Pictures/1669954221209850.png
    fit_mode = fill
}
