require("plugins/nvim-treesitter")
require("plugins/nvlualine")
require("plugins/mason")
require("plugins/neotree")
require("plugins/telescope")
require("plugins/autopairs")
require("plugins/mini")
require("plugins/blink")
require("plugins/rainbow-delims")
require("plugins/which-key")
require("plugins/auto-lsp")
require("plugins/hipatterns")
require("plugins/edgy")
require("plugins/nvim-ts-autotag")
require("plugins/noice")
require("plugins/toggleterm")
-- require("plugins/lspsignature")
